version: '3.9'

services:
  app:
    user: root
    build: 
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - staticfiles_volume:/usr/src/app/staticfiles
    env_file:
      - ./env/backend.env
    ports:
      - 8000:8000
    command: >
      bash -c " /home/appuser/venv/bin/python manage.py collectstatic --noinput &&
         /home/appuser/venv/bin/gunicorn --bind 0.0.0.0:8000 --worker-tmp-dir /dev/shm blog.wsgi:application"
  
  nginx:
    build: ./nginx
    volumes:
      - staticfiles_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file:
      - ./env/db.env
    volumes:
      - app_db:/var/lib/mysql 
volumes:
  staticfiles_volume:
  app_db:







